print('Let\'s count an area of your triangle')
a = float(input('Enter side lenght (cm): '))
h = float(input('Enter height lenght (cm): '))
print('area of your triangle equals', 0.5*a*h, 'cm')
input('press ENTER close this window')
exit(0)
